[supervisord]
nodaemon=true
logfile=/apps/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/apps/logs

[program:manager-server]
directory=/apps/manager-server
command=/apps/manager-server/manager-server
user=xiaozhi
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=20
stopsignal=TERM
stdout_logfile=/apps/logs/manager-server.out.log
stderr_logfile=/apps/logs/manager-server.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:backend-server]
directory=/apps/backend-server
command=/apps/backend-server/backend-server
user=xiaozhi
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=20
stopsignal=TERM
stdout_logfile=/apps/logs/backend-server.out.log
stderr_logfile=/apps/logs/backend-server.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_backups=5
